version: '3'
services:

  scrapper:
    build:
      context: scrapper
      dockerfile: Dockerfile
    container_name: scrapper
    restart: unless-stopped
    environment:
      MONGODB_DATABASE: scrapperdb
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin
      MONGODB_HOSTNAME: mongodb
    volumes:
      - appdata:/var/scrapperapp/
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: scrapperdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /data/logs
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
